version: '3.8'

services:
  php-httpd:
    image: php:8.2-apache
    container_name: whatsapp_webserver
    ports:
      - '8080:80'
    volumes:
      - "./:/var/www/html"
  
  database:
    image: mysql
    container_name: whatsapp_db
    volumes:
      - "mysql-volume:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      TZ: "Europe/Paris"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "whatsapp_db"

  phpmyadmin:
    image: phpmyadmin
    links:
      - 'database:db'
    ports:
      - 8081:80

      
volumes:
  mysql-volume: